name: Deploy

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
      access_key:
        description: access
        required: true
      secret_key:
        description: secret
        required: true
      region:
        description: region
        required: true
      app_id:
        description: region
        required: true

env:
  ENVIRONMENT: ${{ github.event.inputs.environment || 'master' }}
  AWS_ACCESS_KEY_ID: ${{ github.event.inputs.access_key || '123' }}
  AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.secret_key || '123' }}
  AWS_REGION: ${{ github.event.inputs.region || 'eu' }}
  APP_ID: ${{ github.event.inputs.app_id || 'eu' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy project
        run: aws amplify start-deployment --app-id --branch-name ${{ env.ENVIRONMENT }}